=== mil-oss/spdx-xsd/xml/xsd/spdx-license-iep.xsd
<?xml version="1.0"?>
<xs:schema xmlns="spdx:xsd::1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:exsl="http://exslt.org/common" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="spdx:xsd::1.0" version="1">
  <xs:complexType name="LicenseType">
    <xs:annotation>
      <xs:documentation>A data type for License type</xs:documentation>
      <xs:appinfo>
        <ComplexType name="License" xmlname="License" comment="A License represents a copyright license. The SPDX license list website is annotated with these properties (using RDFa) to allow license data published there to be easily processed. The license list is populated in accordance with the License List fields guidelines. These guidelines are not normative and may change over time. SPDX tooling should not rely on values in the license list conforming to the current guidelines." rdf="http://spdx.org/rdf/terms#License" subclassof="SimpleLicensingInfo"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="SimpleLicensingInfoType">
        <xs:sequence>
          <xs:element ref="IsDeprecatedLicenseID" minOccurs="0"/>
          <xs:element ref="IsOsiApprovedIndicator" minOccurs="1"/>
          <xs:element ref="IsFsfLibreIndicator" minOccurs="0"/>
          <xs:element ref="StandardLicenseHeader" minOccurs="0"/>
          <xs:element ref="LicenseText" minOccurs="1"/>
          <xs:element ref="StandardLicenseTemplate" minOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="AnyLicenseInfoType">
    <xs:annotation>
      <xs:documentation>A data type for AnyLicenseInfo type</xs:documentation>
      <xs:appinfo>
        <ComplexType name="AnyLicenseInfo" xmlname="AnyLicenseInfo" comment="The AnyLicenseInfo class includes all resources that represent licensing information." rdf="http://spdx.org/rdf/terms#AnyLicenseInfo" definedby="AnyLicenseInfo"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence/>
  </xs:complexType>
  <xs:complexType name="CommentTextType">
    <xs:annotation>
      <xs:documentation>A data type for CommentText</xs:documentation>
      <xs:appinfo>
        <ComplexType name="comment" xmlname="CommentText" typename="Comment" comment="" rdf="http://www.w3.org/2000/01/rdf-schema#comment"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:complexType>
  <xs:complexType name="IsDeprecatedLicenseIDType">
    <xs:annotation>
      <xs:documentation>A data type that indicates if the license id is Deprecated.</xs:documentation>
      <xs:appinfo>
        <ComplexType name="IsDeprecatedLicenseIDType" comment="Indicates if the license is is Deprecated." rdf="http://spdx.org/rdf/terms#isDeprecatedLicenseId" domain="License" range="Boolean"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:boolean"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IsFsfLibreType">
    <xs:annotation>
      <xs:documentation>A data type to indicate if the license is is FSF Libre.</xs:documentation>
      <xs:appinfo>
        <ComplexType name="IsFsfLibre" comment="Indicates if the license is is FSF Libre." rdf="http://spdx.org/rdf/terms#isFsfLibre" domain="License" range="Boolean"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:boolean"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IsOsiApprovedIndicatorType">
    <xs:annotation>
      <xs:documentation>A data type for Indicates if the OSI has approved the license.</xs:documentation>
      <xs:appinfo>
        <ComplexType name="isOsiApproved" xmlname="IsOsiApprovedIndicator" typename="IsOsiApproved" comment="Indicates if the OSI has approved the license." rdf="http://spdx.org/rdf/terms#isOsiApproved" domain="License" range="Boolean"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:boolean"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="LicenseIDType">
    <xs:annotation>
      <xs:documentation>A data type for A human readable short form license identifier for a license. The license ID is iether on the standard license oist or the form "LicenseRef-"[idString] where [idString] is a unique string containing letters, numbers, ".", "-" or "+".</xs:documentation>
      <xs:appinfo>
        <ComplexType name="licenseId" xmlname="LicenseID" typename="LicenseID" comment="A human readable short form license identifier for a license. The license ID is iether on the standard license oist or the form &quot;LicenseRef-&quot;[idString] where [idString] is a unique string containing letters, numbers, &quot;.&quot;, &quot;-&quot; or &quot;+&quot;." rdf="http://spdx.org/rdf/terms#licenseId" domain="SimpleLicensingInfo" range="String"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="LicenseTextType">
    <xs:annotation>
      <xs:documentation>A data type for Full text of the license.</xs:documentation>
      <xs:appinfo>
        <ComplexType name="licenseText" xmlname="LicenseText" typename="LicenseText" comment="Full text of the license." rdf="http://spdx.org/rdf/terms#licenseText" domain="License" range="String"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="NameType">
    <xs:annotation>
      <xs:documentation>A data type for The full human readable name of the item. This should include version information when applicable.</xs:documentation>
      <xs:appinfo>
        <ComplexType name="name" xmlname="Name" typename="Name" comment="The full human readable name of the item. This should include version information when applicable." rdf="http://spdx.org/rdf/terms#name" domain="SpdxElement" range="String"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SeeAlsoURIType">
    <xs:annotation>
      <xs:documentation>A data type for rdfs:seeAlso is an instance of rdf:Property that is used to indicate a resource that might provide additional information about the subject resource.</xs:documentation>
      <xs:appinfo>
        <ComplexType name="seeAlso" xmlname="SeeAlsoURI" typename="SeeAlso" comment="rdfs:seeAlso is an instance of rdf:Property that is used to indicate a resource that might provide additional information about the subject resource." rdf="http://www.w3.org/2000/01/rdf-schema#seeAlso"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:complexType>
  <xs:complexType name="SimpleLicensingInfoType">
    <xs:annotation>
      <xs:documentation>A data type for SimpleLicensingInfo type</xs:documentation>
      <xs:appinfo>
        <ComplexType name="SimpleLicenseingInfo" xmlname="SimpleLicensingInfo" comment="The SimpleLicenseInfo class includes all resources that represent simple, atomic, licensing information." rdf="http://spdx.org/rdf/terms#SimpleLicenseingInfo" subclassof="AnyLicenseInfo"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="AnyLicenseInfoType">
        <xs:sequence>
          <xs:element ref="LicenseID" minOccurs="1" maxOccurs="1"/>
          <xs:element ref="CommentText" maxOccurs="1"/>
          <xs:element ref="SeeAlsoURI" minOccurs="0"/>
          <xs:element ref="Name" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="StandardLicenseHeaderType">
    <xs:annotation>
      <xs:documentation>A data type for License author's preferred text to indicated that a file is covered by the license.</xs:documentation>
      <xs:appinfo>
        <ComplexType xmlns="" name="standardLicenseHeader" xmlname="StandardLicenseHeader" comment="License author's preferred text to indicated that a file is covered by the license." rdf="http://spdx.org/rdf/terms#standardLicenseHeader" domain="License" range="String"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="StandardLicenseTemplateType">
    <xs:annotation>
      <xs:documentation>A data type for License template which describes sections of the license which can be varied. See License Template section of the specification for format information.</xs:documentation>
      <xs:appinfo>
        <ComplexType xmlns="" name="standardLicenseTemplate" xmlname="StandardLicenseTemplate" comment="License template which describes sections of the license which can be varied. See License Template section of the specification for format information." rdf="http://spdx.org/rdf/terms#standardLicenseTemplate" domain="License" range="String"/>
      </xs:appinfo>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:element name="CommentText" type="CommentTextType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data type for CommentText</xs:documentation>
      <xs:appinfo>
        <Element name="comment" xmlname="CommentText" typename="Comment" comment="" rdf="http://www.w3.org/2000/01/rdf-schema#comment"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="IsDeprecatedLicenseID" type="IsDeprecatedLicenseIDType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data item that indicates if the license id is Deprecated.</xs:documentation>
      <xs:appinfo>
        <Element name="IsDeprecatedLicenseID" comment="Indicates if the license id is Deprecated." rdf="http://spdx.org/rdf/terms#isDeprecatedLicenseId" domain="License" range="Boolean"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="IsFsfLibreIndicator" type="IsFsfLibreType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data item to indicate if the license is FSF Libre.</xs:documentation>
      <xs:appinfo>
        <Element name="IsFsfLibre" comment="Indicates if the license is is FSF Libre." rdf="http://spdx.org/rdf/terms#isFsfLibre" domain="License" range="Boolean"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="IsOsiApprovedIndicator" type="IsOsiApprovedIndicatorType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data type for Indicates if the OSI has approved the license.</xs:documentation>
      <xs:appinfo>
        <Element name="isOsiApproved" xmlname="IsOsiApprovedIndicator" typename="IsOsiApproved" comment="Indicates if the OSI has approved the license." rdf="http://spdx.org/rdf/terms#isOsiApproved" domain="License" range="Boolean"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="License" type="LicenseType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data item for License</xs:documentation>
      <xs:appinfo>
        <Element name="License" xmlname="License" comment="A License represents a copyright license. The SPDX license list website is annotated with these properties (using RDFa) to allow license data published there to be easily processed. The license list is populated in accordance with the License List fields guidelines. These guidelines are not normative and may change over time. SPDX tooling should not rely on values in the license list conforming to the current guidelines." rdf="http://spdx.org/rdf/terms#License" subclassof="SimpleLicensingInfo"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="LicenseID" type="LicenseIDType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data type for A human readable short form license identifier for a license. The license ID is iether on the standard license oist or the form "LicenseRef-"[idString] where [idString] is a unique string containing letters, numbers, ".", "-" or "+".</xs:documentation>
      <xs:appinfo>
        <Element name="licenseId" xmlname="LicenseID" typename="LicenseID" comment="A human readable short form license identifier for a license. The license ID is iether on the standard license oist or the form &quot;LicenseRef-&quot;[idString] where [idString] is a unique string containing letters, numbers, &quot;.&quot;, &quot;-&quot; or &quot;+&quot;." rdf="http://spdx.org/rdf/terms#licenseId" domain="SimpleLicensingInfo" range="String"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="LicenseText" type="LicenseTextType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data type for Full text of the license.</xs:documentation>
      <xs:appinfo>
        <Element name="licenseText" xmlname="LicenseText" typename="LicenseText" comment="Full text of the license." rdf="http://spdx.org/rdf/terms#licenseText" domain="License" range="String"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="Name" type="NameType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data type for The full human readable name of the item. This should include version information when applicable.</xs:documentation>
      <xs:appinfo>
        <Element name="name" xmlname="Name" typename="Name" comment="The full human readable name of the item. This should include version information when applicable." rdf="http://spdx.org/rdf/terms#name" domain="SpdxElement" range="String"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="SeeAlsoURI" type="SeeAlsoURIType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data type for rdfs:seeAlso is an instance of rdf:Property that is used to indicate a resource that might provide additional information about the subject resource.</xs:documentation>
      <xs:appinfo>
        <Element name="seeAlso" xmlname="SeeAlsoURI" typename="SeeAlso" comment="rdfs:seeAlso is an instance of rdf:Property that is used to indicate a resource that might provide additional information about the subject resource." rdf="http://www.w3.org/2000/01/rdf-schema#seeAlso"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="StandardLicenseHeader" type="StandardLicenseHeaderType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data type for License author's preferred text to indicated that a file is covered by the license.</xs:documentation>
      <xs:appinfo>
        <Element xmlns="" name="standardLicenseHeader" xmlname="StandardLicenseHeader" comment="License author's preferred text to indicated that a file is covered by the license." rdf="http://spdx.org/rdf/terms#standardLicenseHeader" domain="License" range="String"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name="StandardLicenseTemplate" type="StandardLicenseTemplateType" nillable="true">
    <xs:annotation>
      <xs:documentation>A data type for License template which describes sections of the license which can be varied. See License Template section of the specification for format information.</xs:documentation>
      <xs:appinfo>
        <Element xmlns="" name="standardLicenseTemplate" xmlname="StandardLicenseTemplate" comment="License template which describes sections of the license which can be varied. See License Template section of the specification for format information." rdf="http://spdx.org/rdf/terms#standardLicenseTemplate" domain="License" range="String"/>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
</xs:schema>

=== mil-oss/spdx-xsd/tmp/spdx-license-iepd/xml/instance/spdx-license-instance.xml
<?xml version="1.0"?>
<License xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:spdx-xml:1.0" xsi:schemaLocation="urn:spdx-xml:1.0 ../xsd/spdx-license-iep.xsd">
  <LicenseID>Test string one</LicenseID>
  <CommentText>Test string one</CommentText>
  <SeeAlsoURI>http://anyuri.org</SeeAlsoURI>
  <Name>Test string one</Name>
  <IsDeprecatedLicenseID>true</IsDeprecatedLicenseID>
  <IsOsiApprovedIndicator>true</IsOsiApprovedIndicator>
  <IsFsfLibreIndicator>true</IsFsfLibreIndicator>
  <StandardLicenseHeaderText>Test string one</StandardLicenseHeaderText>
  <LicenseText>Test string one</LicenseText>
  <StandardLicenseTemplateText>Test string one</StandardLicenseTemplateText>
</License>
